language: python
python:
    - "3.4"
    - "3.5"

install:
    "pip install -r requirements.txt"
before_script:
    - psql -c 'create database pgpydict;' -U postgres
script:
    - "green -v ."
services:
    - postgresql
